CREATE TABLE DEPARTMENT(
EMPLOYEE_ID TEXT,
NAME TEXT,
DEPARTMENT_NAME TEXT,
SALARY INTEGER
);

INSERT INTO DEPARTMENT VALUES
('101', "Steven King", "SALES", 10000),
('102', "Jacob D. Lewis", "SALES", 15800),
('103', "Rhonda B. Goodwyn", "HR", 18880),
('104', "Onuuatuegwu Onyeorulu", "NARKETING", 30000),
('105', "Sophie Marsh", "SALE5", 30000),
('106', "Jake Holmes", "HR", 15000),
('107', "Heng Wu", "HR", 150600),
('108', "Xluxiu Hsoch", "MARKETING", 18603);

SELECT * FROM DEPARTMENT;

SELECT DISTINCT (DEPARTMENT_NAME)
FROM DEPARTMENT;

--GROUP B
SELECT DEPARTMENT_NAME, AVG(SALARY), MIN(SALARY), COUNT(SALARY)
FROM DEPARTMENT
GROUP BY DEPARTMENT_NAME;

-- ORDER BY
SELECT *
FROM DEPARTMENT
ORDER BY DEPARTMENT_NAME , SALARY;